PR dev-refactor-to-python (#11)
* Refactor to python

* Changed var expansion in python job

* Changed env var in python to string

* Changed typo for file context handler

* Changed branch to check out

* Removed main from push to void error

* Updated data/dummy-dirtree-python.md

* Changed formatting and newline

* Updated data/dummy-dirtree-python.md

* Test UTF8 for failing newline output

* Updated data/dummy-dirtree-python.md

* Try UTF8 and u"\r\n" for failing newline output

* Updated data/dummy-dirtree-python.md

* Try append newline with new file context handler each loop

* Updated data/dummy-dirtree-python.md

* Added newline to file handler

* Updated data/dummy-dirtree-python.md

* Delete data directory

* Set OUT_FILE before sparse checkout

* Added create folder and file if not exists

* Added missing os.path for exists

* Refactored env var OUT_FILE usage

* Added os.getenv

* Updated data/dummy-dirtree-python.md

* Switched to workaround csv.writer for multine output

* Updated data/dummy-dirtree-python.md

* Delete data directory

* Added debug print dir and file

* Added out array to write csv at then end of the loop

* Updated data/dummy-dirtree-python.md

* Delete data/dummy-dirtree-python.md

* Updated data/dummy-dirtree-python.md

* Delete data/dummy-dirtree-python.md

* Added append to out as strings inside array

* Updated data/dummy-dirtree-python.md

* Added newline to open file context

* Added default for getenv EXCLUDE and test for list

* Added assert EXCLUDE type list, removed typo getenv OUT_FILE

* Updated data/dummy-dirtree-python.md

* Delete data/dummy-dirtree-python.md

* Added EXCLUDE to list conversion

* Added datetime to out list, removed typo write csv OUT_FILE

* Updated data/dummy-dirtree-python.md

* Added actions/setup-python@v5

* Updated data/dummy-dirtree-python.md

* Create app.py, app script from workflow step

* Delete data/dummy-dirtree-python.md

* Refactored to run app.py, step script transfered to app.py

* Updated data/dummy-dirtree-python.md

* Added main workflow run badge

* Delete data directory

* Create ruff.yml

* Changed out csv newline to None, Added \n in out strings

* Updated data/dummy-dirtree-python.md

* Added CMD_HIGHLIGHT for dirtree highlighting in OUT_FILE

* Added getenv CMD_HIGHLIGHT for dirtree highlighting in OUT_FILE

* Updated data/dummy-dirtree-python.md

* Removed array for out list strings for open() f.write()

* Updated data/dummy-dirtree-python.md

* Added newline around dirtree codeblock, Added tab for indent, Added reversed out loop for write()

* Updated data/dummy-dirtree-python.md

* Changed output indent

* Updated data/dummy-dirtree-python.md

* Removed TODOs

* Added date to every output, Disbled reversed out write()

* Updated data/dummy-dirtree-python.md

* Changed ruff trigger to weekly and manual

* Added default .git to EXCLUDE

* Added comment to EXCLUDE input

* Added APP_DIR env var

* Added env vars and their defaults

* Moved app.py to app

* Delete ./app.py

* Added print APP_DIR for debug

* Added print APP_DIR for debug to prevent error duplicate dir in action

* Added working-directory to run app in

* Added ./ to app working directory

* Removed working-directory, Concatenated APP

* Added ../ to prevent redundant working directory

```python
Run python app/app.py
python: can't open file '/home/runner/work/dirtree-readme-action/dirtree-readme-action/app/app.py': [Errno 2] No such file or directory
Error: Process completed with exit code 2.
```

* Debug working dir of actions/setup-python to run app in subdir

Run python ../app/app.py
python: can't open file '/home/runner/work/dirtree-readme-action/dirtree-readme-action/../app/app.py': [Errno 2] No such file or directory
Error: Process completed with exit code 2.

* Added ref ${{ GITHUB_REF_NAME }} to checkout only current branch

* Changed to github.ref_name

* Added check of git active branch in app step

actions/setup-python does execute on main, not other branch ref therefore app.py is not available

* Create HelloCutyPy to check if it gets listed in actions/setup-python

* Delete app directory

* Create app.py to avoid actions/setup-python not finding ./app

* Delete app directory to debug ./app not found by actions/setup-python

* Create app.py to debug actions/setup-python

* Create app.py to debug actions/setup-python

* Added git ls-files to debug missing ./app

* Disabled sparse checkout to debug ls not finding ./app but git ls-files does

.github/workflows/ruff.yml
.github/workflows/write-dirtree-to-file.yml
HelloCutyPy
LICENSE
README.md
a/app.py
app.py
data/dummy-dirtree-python.md
total 32
drwxr-xr-x 4 runner docker 4096 Jun  9 20:54 .
drwxr-xr-x 3 runner docker 4096 Jun  9 20:54 ..
drwxr-xr-x 8 runner docker 4096 Jun  9 20:54 .git
-rw-r--r-- 1 runner docker    1 Jun  9 20:54 HelloCutyPy
-rw-r--r-- 1 runner docker 1492 Jun  9 20:54 LICENSE
-rw-r--r-- 1 runner docker  516 Jun  9 20:54 README.md
-rw-r--r-- 1 runner docker 1024 Jun  9 20:54 app.py
drwxr-xr-x 2 runner docker 4096 Jun  9 20:54 data

* Enabled python calling ./app/app after sparse checkout found to be the reason

git ls-files
github/workflows/ruff.yml
.github/workflows/write-dirtree-to-file.yml
HelloCutyPy
LICENSE
README.md
a/app.py
app.py
data/dummy-dirtree-python.md

ls -la
total 40
drwxr-xr-x 6 runner docker 4096 Jun  9 20:57 .
drwxr-xr-x 3 runner docker 4096 Jun  9 20:57 ..
drwxr-xr-x 8 runner docker 4096 Jun  9 20:57 .git
drwxr-xr-x 3 runner docker 4096 Jun  9 20:57 .github
-rw-r--r-- 1 runner docker    1 Jun  9 20:57 HelloCutyPy
-rw-r--r-- 1 runner docker 1492 Jun  9 20:57 LICENSE
-rw-r--r-- 1 runner docker  516 Jun  9 20:57 README.md
drwxr-xr-x 2 runner docker 4096 Jun  9 20:57 a
-rw-r--r-- 1 runner docker 1024 Jun  9 20:57 app.py
drwxr-xr-x 2 runner docker 4096 Jun  9 20:57 data

* Delete HelloCutyPy because not needed for debug missing ./app anymore

* Rename app.py to app.py because ./a not needed for debug missing ./app anymore

* Moved EXCLUDE default to right position

* Updated data/dummy-dirtree-python.md

* Changed dir walk algo

* Updated data/dummy-dirtree-python.md

* Delete app.py because it is not needed to debug missing ./app anymore

* Added exclusion of dirs again

* Updated data/dummy-dirtree-python.md

* Refactored exclusion of directories

* Updated data/dummy-dirtree-python.md

* Refactored indent, Added print debog for exclusion

* Updated data/dummy-dirtree-python.md

* Changed exclusion and indention

* Updated data/dummy-dirtree-python.md

* Changed exclusion

* Removed dangling print of exclude_lsit

* Updated data/dummy-dirtree-python.md

* Changed indentation, Added exlusion root debug

* Updated data/dummy-dirtree-python.md

* Changed indentation and print debug exclude

* Updated data/dummy-dirtree-python.md

* Change indention, Refactored exclusion into function

* Removed typo EXCLUDE var

* Updated data/dummy-dirtree-python.md

* Create codeql.yml

* Create dependabot.yml

* Update codeql.yml

* Update dependabot.yml

* Added parser sep to dependabot.yml

* Removed multiple spaces after operator

---------

Co-authored-by: GitHub Action <action@github.com>
Co-authored-by: qte77 <qte@77>